application: palaver
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: web/static/dist

- url: /login/google
  login: required
  script: _go_app
  secure: always

- url: /comments.*
  login: required
  script: _go_app
  secure: always


- url: /.*
  login: optional
  script: _go_app
  secure: always
